"""
UserProfile and players' photos (olympic_warriors/avatars.py): store_photo() validates an
upload, re-encodes it as two WebP squares under fresh names and deletes the files it
replaces once the transaction commits; remove_photo() takes both down the same way, and a
deleted profile (its user's cascade included) takes its files with it. Both read the row
under lock, so a stale copy of the profile can neither dodge a lock nor orphan files. Images
are generated by Pillow in memory, and MEDIA_ROOT is a temporary folder per test.
"""

import io
import os
import re
import struct
import tempfile
import zlib
from unittest import mock

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import DatabaseError, connection, transaction
from django.test import TestCase, override_settings
from django.test.utils import CaptureQueriesContext
from PIL import Image, ImageCms, ImageFile, JpegImagePlugin

from olympic_warriors.avatars import (
    LARGE,
    MAX_BYTES,
    MAX_PIXELS,
    SMALL,
    PhotoError,
    remove_photo,
    store_photo,
)
from olympic_warriors.models import Badge, UserProfile

RED, GREEN, BLUE = (255, 0, 0), (0, 160, 0), (0, 0, 255)


def encode(image, fmt, **options):
    """The bytes of `image` saved as `fmt`."""
    buffer = io.BytesIO()
    image.save(buffer, fmt, **options)
    return buffer.getvalue()


def upload(data, name="photo.jpg"):
    """An uploaded file holding `data`, as the multipart parser hands it over."""
    return SimpleUploadedFile(name, data)


def picture(size=(300, 300), color=GREEN, mode="RGB"):
    """A plain image."""
    return Image.new(mode, size, color)


def png_claiming(width, height):
    """A PNG whose header claims width x height pixels but carries almost no pixel data: only
    its header can be read, so refusing it on its size proves nothing was decoded."""

    def chunk(kind, data):
        crc = zlib.crc32(kind + data) & 0xFFFFFFFF
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", crc)

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(b"\0" * 10))
        + chunk(b"IEND", b"")
    )


def gif_claiming(width, height):
    """A GIF whose header claims width x height pixels: past Pillow's own bomb limit if
    Pillow ever parsed it as a GIF."""
    size = struct.pack("<HH", width, height)
    return b"GIF89a" + size + b"\0\0\0" + b",\0\0\0\0" + size + b"\0\2\2\x44\1\0;"


def sideways():
    """A landscape picture stored sideways: red on the left, blue on the right. EXIF
    orientation 6 asks for a quarter turn clockwise, which puts the red half on top."""
    image = picture((200, 100), BLUE)
    image.paste(RED, (0, 0, 100, 100))
    return image


def with_exif_segment(jpeg, entries, data=b""):
    """`jpeg` with a hand-made EXIF segment right after its start marker: a little-endian
    TIFF header, one IFD of `entries` (tag, type, count, 4 value bytes) and `data` after it,
    at offset 8 + 2 + 12 * len(entries) + 4, where an entry's value can point."""
    tiff = b"II*\0" + struct.pack("<I", 8) + struct.pack("<H", len(entries))
    for tag, kind, count, value in entries:
        tiff += struct.pack("<HHI", tag, kind, count) + value
    payload = b"Exif\0\0" + tiff + struct.pack("<I", 0) + data
    return jpeg[:2] + b"\xff\xe1" + struct.pack(">H", len(payload) + 2) + payload + jpeg[2:]


ORIENTATION_6 = (0x0112, 3, 1, struct.pack("<HH", 6, 0))  # SHORT 6, padded to 4 bytes
AFTER_TWO_ENTRIES = struct.pack("<I", 8 + 2 + 12 * 2 + 4)


def close_to(pixel, color, tolerance=40):
    """Whether an RGB pixel is within `tolerance` of `color` on every channel (lossy
    encodings shift colours a little)."""
    return all(abs(a - b) <= tolerance for a, b in zip(pixel[:3], color))


class MediaRootTestCase(TestCase):
    """A throwaway MEDIA_ROOT per test, removed in tearDown."""

    def setUp(self):
        super().setUp()
        self.media = tempfile.TemporaryDirectory()  # pylint: disable=consider-using-with
        self.media_override = override_settings(MEDIA_ROOT=self.media.name)
        self.media_override.enable()

    def tearDown(self):
        self.media_override.disable()
        self.media.cleanup()
        super().tearDown()

    def exists(self, name):
        """Whether the storage holds a file under `name`."""
        return os.path.exists(os.path.join(self.media.name, name))

    def avatar_files(self):
        """Every file under avatars/, sorted."""
        folder = os.path.join(self.media.name, "avatars")
        return sorted(os.listdir(folder)) if os.path.isdir(folder) else []


class TestUserProfileModel(TestCase):
    def setUp(self):
        self.ana = User.objects.create(username="ana", first_name="Ana", last_name="Lopez")

    def test_a_new_profile_has_nothing_yet(self):
        profile = UserProfile.objects.create(user=self.ana)

        self.assertEqual(self.ana.profile, profile)
        self.assertFalse(profile.photo)
        self.assertFalse(profile.photo_small)
        self.assertFalse(profile.photo_locked)
        self.assertEqual(profile.showcase, [])
        self.assertIsNone(profile.claimed_at)
        self.assertIsNotNone(profile.updated_at)

    def test_the_showcase_holds_at_most_three_catalogue_codes(self):
        C = Badge.Codes
        UserProfile(user=self.ana, showcase=[C.CHAMPION, C.GOAT, C.ROOKIE]).full_clean()

        with self.assertRaises(ValidationError) as four:
            UserProfile(
                user=self.ana, showcase=[C.CHAMPION, C.GOAT, C.ROOKIE, C.VETERAN]
            ).full_clean()
        with self.assertRaises(ValidationError) as unknown:
            UserProfile(user=self.ana, showcase=["no-such-badge"]).full_clean()

        self.assertIn("showcase", four.exception.message_dict)
        self.assertIn("showcase", unknown.exception.message_dict)

    def test_it_goes_with_its_user(self):
        UserProfile.objects.create(user=self.ana)

        self.ana.delete()

        self.assertFalse(UserProfile.objects.exists())


class TestStorePhoto(MediaRootTestCase):
    def setUp(self):
        super().setUp()
        self.ana = User.objects.create(username="ana", first_name="Ana", last_name="Lopez")
        self.profile = UserProfile.objects.create(user=self.ana)

    def stored(self):
        """The two stored images, re-read from the database and the storage."""
        self.profile.refresh_from_db()
        with self.profile.photo.open("rb") as large, self.profile.photo_small.open("rb") as small:
            return Image.open(io.BytesIO(large.read())), Image.open(io.BytesIO(small.read()))

    def refused(self, data, name="photo.jpg"):
        """The PhotoError code store_photo raises for `data`."""
        with self.assertRaises(PhotoError) as caught:
            store_photo(self.profile, upload(data, name))
        return caught.exception.code

    def test_a_jpeg_becomes_two_webp_squares(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))

        large, small = self.stored()
        self.assertEqual((large.format, large.size), ("WEBP", (LARGE, LARGE)))
        self.assertEqual((small.format, small.size), ("WEBP", (SMALL, SMALL)))
        self.assertEqual((LARGE, SMALL), (512, 128))
        self.assertTrue(close_to(large.convert("RGB").getpixel((256, 256)), GREEN))

    def test_the_files_get_fresh_names_under_avatars(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))

        self.profile.refresh_from_db()
        large, small = self.profile.photo.name, self.profile.photo_small.name
        match = re.fullmatch(rf"avatars/{self.ana.id}-([0-9a-f]{{12}})\.webp", large)
        self.assertIsNotNone(match, large)
        self.assertEqual(small, f"avatars/{self.ana.id}-{match.group(1)}-sm.webp")
        self.assertEqual(self.profile.photo_small.url, f"/media/{small}")
        self.assertTrue(self.exists(large))
        self.assertTrue(self.exists(small))

    def assert_upright(self):
        """The stored photo is the sideways() picture turned upright: red on top."""
        large, _ = self.stored()
        pixels = large.convert("RGB")
        for x in (40, 256, 470):
            self.assertTrue(close_to(pixels.getpixel((x, 40)), RED), (x, pixels.getpixel((x, 40))))
            self.assertTrue(close_to(pixels.getpixel((x, 470)), BLUE))

    def test_an_exif_rotated_jpeg_comes_out_upright_without_its_metadata(self):
        exif = Image.Exif()
        exif[0x0112] = 6  # Orientation
        exif[0x010F] = "PhoneMaker"  # Make
        exif[0x8825] = {1: "N", 2: (48.0, 51.0, 24.0)}  # GPSInfo: latitude
        icc = ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes()
        xmp = b"<x:xmpmeta xmlns:x='adobe:ns:meta/'>Somewhere, 48.85 N</x:xmpmeta>"
        data = encode(sideways(), "JPEG", exif=exif, icc_profile=icc, xmp=xmp, quality=95)
        self.assertTrue({"exif", "icc_profile", "xmp"} <= set(Image.open(io.BytesIO(data)).info))
        real_save, handed = Image.Image.save, []

        def spy(image, fp, format=None, **params):  # pylint: disable=redefined-builtin
            handed.append(dict(image.info))
            return real_save(image, fp, format, **params)

        with mock.patch.object(Image.Image, "save", spy):
            store_photo(self.profile, upload(data))

        self.assert_upright()
        # Nothing reaches the encoder, whatever the encoder would keep.
        self.assertEqual(handed, [{}, {}])
        for image in self.stored():
            self.assertEqual(dict(image.getexif()), {})
            self.assertFalse({"exif", "icc_profile", "xmp"} & set(image.info), image.info)

    def test_a_corrupt_exif_block_neither_fails_nor_refuses_the_photo(self):
        jpeg = encode(sideways(), "JPEG", quality=95)
        for name, data, upright in (
            # Pillow's exif_transpose() raised AttributeError re-encoding this one (a DOUBLE
            # where the Software tag wants text), and struct.error on the next one (a
            # negative SRATIONAL over zero); the orientation itself reads fine in both.
            (
                "double software",
                with_exif_segment(
                    jpeg,
                    [ORIENTATION_6, (0x0131, 12, 1, AFTER_TWO_ENTRIES)],
                    struct.pack("<d", float("nan")),
                ),
                True,
            ),
            (
                "negative srational",
                with_exif_segment(
                    jpeg,
                    [ORIENTATION_6, (0x9201, 10, 1, AFTER_TWO_ENTRIES)],
                    struct.pack("<ii", -1, 0),
                ),
                True,
            ),
            ("garbage", jpeg[:2] + b"\xff\xe1\0\x1aExif\0\0" + b"\x13\x37" * 9 + jpeg[2:], False),
        ):
            with self.subTest(name):
                store_photo(self.profile, upload(data))

                if upright:
                    self.assert_upright()
                else:
                    large, _ = self.stored()
                    self.assertEqual(large.size, (LARGE, LARGE))

    def test_a_png_is_accepted_and_its_transparency_flattened_on_grey(self):
        clear = picture((200, 200), (255, 0, 0, 0), mode="RGBA")
        clear.paste((0, 0, 255, 255), (50, 50, 150, 150))
        store_photo(self.profile, upload(encode(clear, "PNG"), "photo.png"))

        large, _ = self.stored()
        pixels = large.convert("RGB")
        self.assertEqual(large.mode, "RGB")
        self.assertTrue(close_to(pixels.getpixel((10, 10)), (128, 128, 128), 10))
        self.assertTrue(close_to(pixels.getpixel((256, 256)), BLUE))

    def test_a_palette_png_and_a_webp_are_accepted(self):
        store_photo(self.profile, upload(encode(picture().convert("P"), "PNG"), "a.png"))
        store_photo(self.profile, upload(encode(picture(), "WEBP"), "a.webp"))

        large, small = self.stored()
        self.assertEqual((large.size, small.size), ((LARGE, LARGE), (SMALL, SMALL)))

    def test_a_multi_picture_jpeg_uses_its_first_picture(self):
        second = picture(color=RED)
        data = encode(picture(color=GREEN), "MPO", save_all=True, append_images=[second])
        self.assertEqual(Image.open(io.BytesIO(data)).format, "MPO")

        store_photo(self.profile, upload(data))

        large, _ = self.stored()
        self.assertTrue(close_to(large.convert("RGB").getpixel((256, 256)), GREEN))

    def test_a_non_square_image_is_centre_cropped(self):
        for size, boxes in (
            ((300, 100), ((0, 0, 100, 100), (200, 0, 300, 100))),  # landscape
            ((100, 300), ((0, 0, 100, 100), (0, 200, 100, 300))),  # portrait
        ):
            with self.subTest(size=size):
                image = picture(size, GREEN)
                image.paste(RED, boxes[0])
                image.paste(BLUE, boxes[1])
                store_photo(self.profile, upload(encode(image, "PNG"), "a.png"))

                large, _ = self.stored()
                pixels = large.convert("RGB")
                for corner in ((5, 5), (506, 5), (5, 506), (506, 506), (256, 256)):
                    self.assertTrue(close_to(pixels.getpixel(corner), GREEN), corner)

    def test_a_gif_or_a_text_file_is_refused(self):
        gif = encode(picture(), "GIF")

        self.assertEqual(self.refused(gif, "photo.gif"), "bad_format")
        self.assertEqual(self.refused(b"not an image at all", "photo.jpg"), "bad_format")
        self.assertEqual(self.refused(b"", "photo.jpg"), "bad_format")
        self.assertEqual(self.avatar_files(), [])

    def test_other_formats_are_never_parsed(self):
        # Parsed as a GIF, this header would trip Pillow's bomb guard (too_many_pixels):
        # only the accepted formats' parsers ever read an upload.
        self.assertEqual(self.refused(gif_claiming(20000, 20000), "photo.gif"), "bad_format")

    def test_only_the_accepted_formats_pass_whatever_opens(self):
        gif = Image.open(io.BytesIO(encode(picture(), "GIF")))

        with mock.patch("olympic_warriors.avatars.Image.open", return_value=gif):
            self.assertEqual(self.refused(b"anything"), "bad_format")
        self.assertEqual(self.avatar_files(), [])

    def test_a_broken_image_is_refused(self):
        truncated = encode(picture((400, 400)), "JPEG")[:600]

        self.assertEqual(self.refused(truncated), "bad_format")

    def test_nothing_uploaded_is_missing(self):
        with self.assertRaises(PhotoError) as caught:
            store_photo(self.profile, None)

        self.assertEqual(caught.exception.code, "missing")

    def test_more_than_2_mb_is_refused_before_reading_it(self):
        png = encode(picture(), "PNG")
        # Pillow ignores anything after IEND: this is a valid image of exactly 2 MB.
        exactly = png + b"\0" * (MAX_BYTES - len(png))
        self.assertEqual(MAX_BYTES, 2 * 1024 * 1024)

        with mock.patch("olympic_warriors.avatars.Image.open") as opened:
            self.assertEqual(self.refused(exactly + b"\0", "a.png"), "too_large")
        opened.assert_not_called()
        store_photo(self.profile, upload(exactly, "a.png"))
        self.assertEqual(len(self.avatar_files()), 2)

    def test_more_than_4096_squared_pixels_is_refused_without_decoding(self):
        self.assertEqual(MAX_PIXELS, 4096 * 4096)
        one_row_too_many = encode(picture((4096, 4097), 1, mode="1"), "PNG")  # a few KB

        with mock.patch.object(
            ImageFile.ImageFile, "load", side_effect=AssertionError("decoded")
        ) as load:
            self.assertEqual(self.refused(one_row_too_many, "a.png"), "too_many_pixels")
            self.assertEqual(self.refused(png_claiming(5000, 5000), "a.png"), "too_many_pixels")
        load.assert_not_called()

    def test_pillow_s_own_bomb_guards_read_as_too_many_pixels(self):
        # 10000² trips Pillow's DecompressionBombWarning, 20000² its DecompressionBombError,
        # both while the header is read. The module's own cap is lifted out of the way, so
        # only Pillow's guards can refuse them.
        with mock.patch("olympic_warriors.avatars.MAX_PIXELS", 10**12):
            self.assertEqual(self.refused(png_claiming(10000, 10000), "a.png"), "too_many_pixels")
            self.assertEqual(self.refused(png_claiming(20000, 20000), "a.png"), "too_many_pixels")

    def test_exactly_4096_squared_pixels_is_accepted(self):
        store_photo(self.profile, upload(encode(picture((4096, 4096), 1, mode="1"), "PNG")))

        large, small = self.stored()
        self.assertEqual((large.size, small.size), ((LARGE, LARGE), (SMALL, SMALL)))

    def test_a_large_jpeg_is_decoded_at_a_reduced_scale(self):
        real_draft = JpegImagePlugin.JpegImageFile.draft
        with mock.patch.object(
            JpegImagePlugin.JpegImageFile, "draft", autospec=True, side_effect=real_draft
        ) as draft:
            store_photo(self.profile, upload(encode(picture((3000, 2000)), "JPEG")))

        draft.assert_called_once_with(mock.ANY, "RGB", (1024, 1024))
        large, small = self.stored()
        self.assertEqual((large.size, small.size), ((LARGE, LARGE), (SMALL, SMALL)))

    def test_a_locked_profile_refuses_an_upload(self):
        self.profile.photo_locked = True
        self.profile.save()

        self.assertEqual(self.refused(encode(picture(), "JPEG")), "photo_locked")
        with self.assertRaises(PhotoError) as nothing:
            store_photo(self.profile, None)
        self.assertEqual(nothing.exception.code, "photo_locked")
        self.profile.refresh_from_db()
        self.assertFalse(self.profile.photo)
        self.assertEqual(self.avatar_files(), [])

    def test_a_lock_set_since_the_profile_was_read_refuses_the_upload(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        stale = UserProfile.objects.get(pk=self.profile.pk)  # read before the moderation
        with self.captureOnCommitCallbacks(execute=True):  # « Retirer et verrouiller »
            moderated = UserProfile.objects.get(pk=self.profile.pk)
            moderated.photo_locked = True
            moderated.save()
            remove_photo(moderated)

        with self.captureOnCommitCallbacks(execute=True):
            with self.assertRaises(PhotoError) as caught:
                store_photo(stale, upload(encode(picture(color=RED), "JPEG")))

        self.assertEqual(caught.exception.code, "photo_locked")
        self.profile.refresh_from_db()
        self.assertEqual((self.profile.photo.name, self.profile.photo_small.name), ("", ""))
        self.assertEqual(self.avatar_files(), [])

    def test_replacing_deletes_the_old_files_once_committed(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        old = (self.profile.photo.name, self.profile.photo_small.name)

        with self.captureOnCommitCallbacks(execute=True) as callbacks:
            store_photo(self.profile, upload(encode(picture(color=RED), "JPEG")))
            self.assertTrue(all(self.exists(name) for name in old))  # not before the commit

        self.profile.refresh_from_db()
        new = (self.profile.photo.name, self.profile.photo_small.name)
        self.assertEqual(len(callbacks), 2)  # one per file
        pattern = rf"avatars/{self.ana.id}-([0-9a-f]{{12}})(-sm)?\.webp"
        tokens = [re.fullmatch(pattern, name) for name in (*old, *new)]
        self.assertTrue(all(tokens), (old, new))
        self.assertEqual(tokens[0].group(1), tokens[1].group(1))
        self.assertEqual(tokens[2].group(1), tokens[3].group(1))
        self.assertNotEqual(tokens[0].group(1), tokens[2].group(1))
        self.assertFalse(any(self.exists(name) for name in old))
        self.assertTrue(all(self.exists(name) for name in new))
        self.assertEqual(sorted(self.avatar_files()), sorted(os.path.basename(n) for n in new))

    def test_replacing_deletes_the_files_the_row_holds_not_a_stale_copy(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        stale = UserProfile.objects.get(pk=self.profile.pk)
        with self.captureOnCommitCallbacks(execute=True):  # meanwhile, another upload
            fresh = UserProfile.objects.get(pk=self.profile.pk)
            store_photo(fresh, upload(encode(picture(), "PNG")))

        with self.captureOnCommitCallbacks(execute=True):
            store_photo(stale, upload(encode(picture(color=RED), "JPEG")))

        self.profile.refresh_from_db()
        current = (self.profile.photo.name, self.profile.photo_small.name)
        self.assertEqual(self.avatar_files(), sorted(os.path.basename(n) for n in current))

    def test_a_failed_save_deletes_the_new_files_and_restores_the_profile(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        old = (self.profile.photo.name, self.profile.photo_small.name)

        with self.captureOnCommitCallbacks(execute=True) as callbacks, mock.patch.object(
            UserProfile, "save", side_effect=DatabaseError("the row went away")
        ):
            with self.assertRaises(DatabaseError):
                store_photo(self.profile, upload(encode(picture(color=RED), "JPEG")))

        self.assertEqual(callbacks, [])
        self.assertEqual((self.profile.photo.name, self.profile.photo_small.name), old)
        self.assertEqual(self.avatar_files(), sorted(os.path.basename(n) for n in old))
        stored = UserProfile.objects.get(pk=self.profile.pk)
        self.assertEqual((stored.photo.name, stored.photo_small.name), old)

    def test_a_file_that_cannot_be_deleted_does_not_keep_the_other(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        stuck, other = self.profile.photo.name, self.profile.photo_small.name
        real_delete = FileSystemStorage.delete

        def delete(storage, name):
            if name == stuck:
                raise PermissionError(name)
            return real_delete(storage, name)

        with mock.patch.object(FileSystemStorage, "delete", delete), self.assertLogs(
            "django", "ERROR"
        ):
            with self.captureOnCommitCallbacks(execute=True):
                store_photo(self.profile, upload(encode(picture(color=RED), "JPEG")))

        self.assertTrue(self.exists(stuck))
        self.assertFalse(self.exists(other))

    def test_a_refused_upload_keeps_the_current_photo(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        current = (self.profile.photo.name, self.profile.photo_small.name)

        with self.captureOnCommitCallbacks(execute=True):
            self.assertEqual(self.refused(b"GIF89a nope", "a.gif"), "bad_format")

        self.profile.refresh_from_db()
        self.assertEqual((self.profile.photo.name, self.profile.photo_small.name), current)
        self.assertTrue(all(self.exists(name) for name in current))
        self.assertEqual(len(self.avatar_files()), 2)


class TestRemovePhoto(MediaRootTestCase):
    def setUp(self):
        super().setUp()
        self.ana = User.objects.create(username="ana", first_name="Ana", last_name="Lopez")
        self.profile = UserProfile.objects.create(user=self.ana)
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        self.names = (self.profile.photo.name, self.profile.photo_small.name)

    def test_it_clears_both_fields_and_deletes_the_files_once_committed(self):
        with self.captureOnCommitCallbacks(execute=True):
            self.assertTrue(remove_photo(self.profile))
            self.assertTrue(all(self.exists(name) for name in self.names))

        self.profile.refresh_from_db()
        self.assertEqual((self.profile.photo.name, self.profile.photo_small.name), ("", ""))
        self.assertEqual(self.avatar_files(), [])

    def test_it_works_on_a_locked_profile(self):
        self.profile.photo_locked = True
        self.profile.save()

        with self.captureOnCommitCallbacks(execute=True):
            self.assertTrue(remove_photo(self.profile))

        self.profile.refresh_from_db()
        self.assertFalse(self.profile.photo)
        self.assertTrue(self.profile.photo_locked)
        self.assertEqual(self.avatar_files(), [])

    def test_without_a_photo_it_writes_nothing(self):
        with self.captureOnCommitCallbacks(execute=True):
            remove_photo(self.profile)
        stamp = UserProfile.objects.get(pk=self.profile.pk).updated_at

        with self.captureOnCommitCallbacks(execute=True) as callbacks, CaptureQueriesContext(
            connection
        ) as queries:
            self.assertFalse(remove_photo(self.profile))

        self.assertEqual(callbacks, [])
        self.assertFalse([q["sql"] for q in queries if q["sql"].startswith("UPDATE")])
        self.assertEqual(UserProfile.objects.get(pk=self.profile.pk).updated_at, stamp)

    def test_it_removes_what_the_row_holds_not_a_stale_copy(self):
        with self.captureOnCommitCallbacks(execute=True):
            remove_photo(self.profile)
        stale = UserProfile.objects.get(pk=self.profile.pk)  # no photo yet
        store_photo(UserProfile.objects.get(pk=self.profile.pk), upload(encode(picture(), "PNG")))

        with self.captureOnCommitCallbacks(execute=True):
            self.assertTrue(remove_photo(stale))

        self.profile.refresh_from_db()
        self.assertFalse(self.profile.photo)
        self.assertEqual(self.avatar_files(), [])


class TestErasure(MediaRootTestCase):
    """A profile's files go with it, whether it is deleted itself or with its user, once
    the deletion commits."""

    def setUp(self):
        super().setUp()
        self.ana = User.objects.create(username="ana", first_name="Ana", last_name="Lopez")
        self.profile = UserProfile.objects.create(user=self.ana)
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.assertEqual(len(self.avatar_files()), 2)

    def test_deleting_the_user_deletes_the_files(self):
        with self.captureOnCommitCallbacks(execute=True):
            self.ana.delete()
            self.assertEqual(len(self.avatar_files()), 2)  # not before the commit

        self.assertEqual(self.avatar_files(), [])

    def test_deleting_the_profile_deletes_the_files(self):
        with self.captureOnCommitCallbacks(execute=True):
            UserProfile.objects.filter(pk=self.profile.pk).delete()

        self.assertEqual(self.avatar_files(), [])

    def test_a_rolled_back_deletion_keeps_them(self):
        with self.captureOnCommitCallbacks(execute=True) as callbacks:
            with self.assertRaises(RuntimeError), transaction.atomic():
                self.ana.delete()
                raise RuntimeError("changed my mind")

        self.assertEqual(callbacks, [])
        self.assertEqual(len(self.avatar_files()), 2)
        self.assertTrue(UserProfile.objects.filter(pk=self.profile.pk).exists())

    def test_a_profile_without_a_photo_leaves_nothing_to_do(self):
        bob = User.objects.create(username="bob")
        UserProfile.objects.create(user=bob)

        with self.captureOnCommitCallbacks(execute=True) as callbacks:
            bob.delete()

        self.assertEqual(callbacks, [])
        self.assertEqual(len(self.avatar_files()), 2)  # Ana's
