"""
UserProfile and players' photos (olympic_warriors/avatars.py): store_photo() validates an
upload, re-encodes it as two WebP squares under fresh names and deletes the files it
replaces once the transaction commits; remove_photo() takes both down the same way. Images
are generated by Pillow in memory, and MEDIA_ROOT is a temporary folder per test.
"""

import io
import os
import re
import struct
import tempfile
import zlib
from unittest import mock

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase, override_settings
from PIL import Image, ImageFile

from olympic_warriors.avatars import (
    LARGE,
    MAX_BYTES,
    MAX_PIXELS,
    SMALL,
    PhotoError,
    remove_photo,
    store_photo,
)
from olympic_warriors.models import Badge, UserProfile

RED, GREEN, BLUE = (255, 0, 0), (0, 160, 0), (0, 0, 255)


def encode(image, fmt, **options):
    """The bytes of `image` saved as `fmt`."""
    buffer = io.BytesIO()
    image.save(buffer, fmt, **options)
    return buffer.getvalue()


def upload(data, name="photo.jpg"):
    """An uploaded file holding `data`, as the multipart parser hands it over."""
    return SimpleUploadedFile(name, data)


def picture(size=(300, 300), color=GREEN, mode="RGB"):
    """A plain image."""
    return Image.new(mode, size, color)


def png_claiming(width, height):
    """A PNG whose header claims width x height pixels but carries almost no pixel data: only
    its header can be read, so refusing it on its size proves nothing was decoded."""

    def chunk(kind, data):
        crc = zlib.crc32(kind + data) & 0xFFFFFFFF
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", crc)

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(b"\0" * 10))
        + chunk(b"IEND", b"")
    )


def close_to(pixel, color, tolerance=40):
    """Whether an RGB pixel is within `tolerance` of `color` on every channel (lossy
    encodings shift colours a little)."""
    return all(abs(a - b) <= tolerance for a, b in zip(pixel[:3], color))


class MediaRootTestCase(TestCase):
    """A throwaway MEDIA_ROOT per test, removed in tearDown."""

    def setUp(self):
        super().setUp()
        self.media = tempfile.TemporaryDirectory()  # pylint: disable=consider-using-with
        self.media_override = override_settings(MEDIA_ROOT=self.media.name)
        self.media_override.enable()

    def tearDown(self):
        self.media_override.disable()
        self.media.cleanup()
        super().tearDown()

    def exists(self, name):
        """Whether the storage holds a file under `name`."""
        return os.path.exists(os.path.join(self.media.name, name))

    def avatar_files(self):
        """Every file under avatars/, sorted."""
        folder = os.path.join(self.media.name, "avatars")
        return sorted(os.listdir(folder)) if os.path.isdir(folder) else []


class TestUserProfileModel(TestCase):
    def setUp(self):
        self.ana = User.objects.create(username="ana", first_name="Ana", last_name="Lopez")

    def test_a_new_profile_has_nothing_yet(self):
        profile = UserProfile.objects.create(user=self.ana)

        self.assertEqual(self.ana.profile, profile)
        self.assertFalse(profile.photo)
        self.assertFalse(profile.photo_small)
        self.assertFalse(profile.photo_locked)
        self.assertEqual(profile.showcase, [])
        self.assertIsNone(profile.claimed_at)
        self.assertIsNotNone(profile.updated_at)

    def test_the_showcase_holds_at_most_three_catalogue_codes(self):
        C = Badge.Codes
        UserProfile(user=self.ana, showcase=[C.CHAMPION, C.GOAT, C.ROOKIE]).full_clean()

        with self.assertRaises(ValidationError) as four:
            UserProfile(
                user=self.ana, showcase=[C.CHAMPION, C.GOAT, C.ROOKIE, C.VETERAN]
            ).full_clean()
        with self.assertRaises(ValidationError) as unknown:
            UserProfile(user=self.ana, showcase=["no-such-badge"]).full_clean()

        self.assertIn("showcase", four.exception.message_dict)
        self.assertIn("showcase", unknown.exception.message_dict)

    def test_it_goes_with_its_user(self):
        UserProfile.objects.create(user=self.ana)

        self.ana.delete()

        self.assertFalse(UserProfile.objects.exists())


class TestStorePhoto(MediaRootTestCase):
    def setUp(self):
        super().setUp()
        self.ana = User.objects.create(username="ana", first_name="Ana", last_name="Lopez")
        self.profile = UserProfile.objects.create(user=self.ana)

    def stored(self):
        """The two stored images, re-read from the database and the storage."""
        self.profile.refresh_from_db()
        with self.profile.photo.open("rb") as large, self.profile.photo_small.open("rb") as small:
            return Image.open(io.BytesIO(large.read())), Image.open(io.BytesIO(small.read()))

    def refused(self, data, name="photo.jpg"):
        """The PhotoError code store_photo raises for `data`."""
        with self.assertRaises(PhotoError) as caught:
            store_photo(self.profile, upload(data, name))
        return caught.exception.code

    def test_a_jpeg_becomes_two_webp_squares(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))

        large, small = self.stored()
        self.assertEqual((large.format, large.size), ("WEBP", (LARGE, LARGE)))
        self.assertEqual((small.format, small.size), ("WEBP", (SMALL, SMALL)))
        self.assertEqual((LARGE, SMALL), (512, 128))
        self.assertTrue(close_to(large.convert("RGB").getpixel((256, 256)), GREEN))

    def test_the_files_get_fresh_names_under_avatars(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))

        self.profile.refresh_from_db()
        large, small = self.profile.photo.name, self.profile.photo_small.name
        match = re.fullmatch(rf"avatars/{self.ana.id}-([0-9a-f]{{12}})\.webp", large)
        self.assertIsNotNone(match, large)
        self.assertEqual(small, f"avatars/{self.ana.id}-{match.group(1)}-sm.webp")
        self.assertEqual(self.profile.photo_small.url, f"/media/{small}")
        self.assertTrue(self.exists(large))
        self.assertTrue(self.exists(small))

    def test_an_exif_rotated_jpeg_comes_out_upright_without_its_exif(self):
        # Stored sideways: red on the left, blue on the right. Orientation 6 asks for a
        # quarter turn clockwise, which puts the red half on top.
        sideways = picture((200, 100), BLUE)
        sideways.paste(RED, (0, 0, 100, 100))
        exif = Image.Exif()
        exif[0x0112] = 6  # Orientation
        exif[0x010F] = "PhoneMaker"  # Make
        exif[0x8825] = {1: "N", 2: (48.0, 51.0, 24.0)}  # GPSInfo: latitude
        store_photo(self.profile, upload(encode(sideways, "JPEG", exif=exif, quality=95)))

        large, small = self.stored()
        pixels = large.convert("RGB")
        for x in (40, 256, 470):
            self.assertTrue(close_to(pixels.getpixel((x, 40)), RED), (x, pixels.getpixel((x, 40))))
            self.assertTrue(close_to(pixels.getpixel((x, 470)), BLUE))
        for image in (large, small):
            self.assertEqual(dict(image.getexif()), {})
            self.assertNotIn("exif", image.info)

    def test_a_png_is_accepted_and_its_transparency_flattened_on_grey(self):
        clear = picture((200, 200), (255, 0, 0, 0), mode="RGBA")
        clear.paste((0, 0, 255, 255), (50, 50, 150, 150))
        store_photo(self.profile, upload(encode(clear, "PNG"), "photo.png"))

        large, _ = self.stored()
        pixels = large.convert("RGB")
        self.assertEqual(large.mode, "RGB")
        self.assertTrue(close_to(pixels.getpixel((10, 10)), (128, 128, 128), 10))
        self.assertTrue(close_to(pixels.getpixel((256, 256)), BLUE))

    def test_a_palette_png_and_a_webp_are_accepted(self):
        store_photo(self.profile, upload(encode(picture().convert("P"), "PNG"), "a.png"))
        store_photo(self.profile, upload(encode(picture(), "WEBP"), "a.webp"))

        large, small = self.stored()
        self.assertEqual((large.size, small.size), ((LARGE, LARGE), (SMALL, SMALL)))

    def test_a_non_square_image_is_centre_cropped(self):
        for size, boxes in (
            ((300, 100), ((0, 0, 100, 100), (200, 0, 300, 100))),  # landscape
            ((100, 300), ((0, 0, 100, 100), (0, 200, 100, 300))),  # portrait
        ):
            with self.subTest(size=size):
                image = picture(size, GREEN)
                image.paste(RED, boxes[0])
                image.paste(BLUE, boxes[1])
                store_photo(self.profile, upload(encode(image, "PNG"), "a.png"))

                large, _ = self.stored()
                pixels = large.convert("RGB")
                for corner in ((5, 5), (506, 5), (5, 506), (506, 506), (256, 256)):
                    self.assertTrue(close_to(pixels.getpixel(corner), GREEN), corner)

    def test_a_gif_or_a_text_file_is_refused(self):
        gif = encode(picture(), "GIF")

        self.assertEqual(self.refused(gif, "photo.gif"), "bad_format")
        self.assertEqual(self.refused(b"not an image at all", "photo.jpg"), "bad_format")
        self.assertEqual(self.refused(b"", "photo.jpg"), "bad_format")
        self.assertEqual(self.avatar_files(), [])

    def test_a_broken_image_is_refused(self):
        truncated = encode(picture((400, 400)), "JPEG")[:600]

        self.assertEqual(self.refused(truncated), "bad_format")

    def test_nothing_uploaded_is_missing(self):
        with self.assertRaises(PhotoError) as caught:
            store_photo(self.profile, None)

        self.assertEqual(caught.exception.code, "missing")

    def test_more_than_2_mb_is_refused_before_reading_it(self):
        png = encode(picture(), "PNG")
        # Pillow ignores anything after IEND: this is a valid image of exactly 2 MB.
        exactly = png + b"\0" * (MAX_BYTES - len(png))
        self.assertEqual(MAX_BYTES, 2 * 1024 * 1024)

        with mock.patch("olympic_warriors.avatars.Image.open") as opened:
            self.assertEqual(self.refused(exactly + b"\0", "a.png"), "too_large")
        opened.assert_not_called()
        store_photo(self.profile, upload(exactly, "a.png"))
        self.assertEqual(len(self.avatar_files()), 2)

    def test_more_than_4096_squared_pixels_is_refused_without_decoding(self):
        self.assertEqual(MAX_PIXELS, 4096 * 4096)
        one_row_too_many = encode(picture((4096, 4097), 1, mode="1"), "PNG")  # a few KB

        with mock.patch.object(
            ImageFile.ImageFile, "load", side_effect=AssertionError("decoded")
        ) as load:
            self.assertEqual(self.refused(one_row_too_many, "a.png"), "too_many_pixels")
            self.assertEqual(self.refused(png_claiming(5000, 5000), "a.png"), "too_many_pixels")
        load.assert_not_called()

    def test_pillow_s_own_bomb_guards_read_as_too_many_pixels(self):
        # 10000² trips Pillow's DecompressionBombWarning, 20000² its DecompressionBombError,
        # both while the header is read. The module's own cap is lifted out of the way, so
        # only Pillow's guards can refuse them.
        with mock.patch("olympic_warriors.avatars.MAX_PIXELS", 10**12):
            self.assertEqual(self.refused(png_claiming(10000, 10000), "a.png"), "too_many_pixels")
            self.assertEqual(self.refused(png_claiming(20000, 20000), "a.png"), "too_many_pixels")

    def test_exactly_4096_squared_pixels_is_accepted(self):
        store_photo(self.profile, upload(encode(picture((4096, 4096), 1, mode="1"), "PNG")))

        large, small = self.stored()
        self.assertEqual((large.size, small.size), ((LARGE, LARGE), (SMALL, SMALL)))

    def test_a_locked_profile_refuses_an_upload(self):
        self.profile.photo_locked = True
        self.profile.save()

        self.assertEqual(self.refused(encode(picture(), "JPEG")), "photo_locked")
        with self.assertRaises(PhotoError) as nothing:
            store_photo(self.profile, None)
        self.assertEqual(nothing.exception.code, "photo_locked")
        self.profile.refresh_from_db()
        self.assertFalse(self.profile.photo)
        self.assertEqual(self.avatar_files(), [])

    def test_replacing_deletes_the_old_files_once_committed(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        old = (self.profile.photo.name, self.profile.photo_small.name)

        with self.captureOnCommitCallbacks(execute=True) as callbacks:
            store_photo(self.profile, upload(encode(picture(color=RED), "JPEG")))
            self.assertTrue(all(self.exists(name) for name in old))  # not before the commit

        self.profile.refresh_from_db()
        new = (self.profile.photo.name, self.profile.photo_small.name)
        self.assertEqual(len(callbacks), 1)
        self.assertNotEqual(new, old)
        self.assertFalse(any(self.exists(name) for name in old))
        self.assertTrue(all(self.exists(name) for name in new))
        self.assertEqual(sorted(self.avatar_files()), sorted(os.path.basename(n) for n in new))

    def test_a_refused_upload_keeps_the_current_photo(self):
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        current = (self.profile.photo.name, self.profile.photo_small.name)

        with self.captureOnCommitCallbacks(execute=True):
            self.assertEqual(self.refused(b"GIF89a nope", "a.gif"), "bad_format")

        self.profile.refresh_from_db()
        self.assertEqual((self.profile.photo.name, self.profile.photo_small.name), current)
        self.assertTrue(all(self.exists(name) for name in current))
        self.assertEqual(len(self.avatar_files()), 2)


class TestRemovePhoto(MediaRootTestCase):
    def setUp(self):
        super().setUp()
        self.ana = User.objects.create(username="ana", first_name="Ana", last_name="Lopez")
        self.profile = UserProfile.objects.create(user=self.ana)
        store_photo(self.profile, upload(encode(picture(), "JPEG")))
        self.profile.refresh_from_db()
        self.names = (self.profile.photo.name, self.profile.photo_small.name)

    def test_it_clears_both_fields_and_deletes_the_files_once_committed(self):
        with self.captureOnCommitCallbacks(execute=True):
            self.assertTrue(remove_photo(self.profile))
            self.assertTrue(all(self.exists(name) for name in self.names))

        self.profile.refresh_from_db()
        self.assertEqual((self.profile.photo.name, self.profile.photo_small.name), ("", ""))
        self.assertEqual(self.avatar_files(), [])

    def test_it_works_on_a_locked_profile(self):
        self.profile.photo_locked = True
        self.profile.save()

        with self.captureOnCommitCallbacks(execute=True):
            self.assertTrue(remove_photo(self.profile))

        self.profile.refresh_from_db()
        self.assertFalse(self.profile.photo)
        self.assertTrue(self.profile.photo_locked)
        self.assertEqual(self.avatar_files(), [])

    def test_without_a_photo_it_writes_nothing(self):
        with self.captureOnCommitCallbacks(execute=True):
            remove_photo(self.profile)
        stamp = UserProfile.objects.get(pk=self.profile.pk).updated_at

        with self.captureOnCommitCallbacks(execute=True) as callbacks, self.assertNumQueries(0):
            self.assertFalse(remove_photo(self.profile))

        self.assertEqual(callbacks, [])
        self.assertEqual(UserProfile.objects.get(pk=self.profile.pk).updated_at, stamp)
