# Generated by Django 4.2.14 on 2024-08-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "olympic_warriors",
            "0002_blindtestguess_is_active_gameevent_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="olympic_warriors.team",
            ),
        ),
    ]
