# Generated by Django 4.2.14 on 2024-08-07 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0003_alter_player_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="captain",
        ),
    ]
