# Generated by Django 4.2.14 on 2024-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrating',
            name='identifier',
            field=models.CharField(max_length=5),
        ),
    ]
