# Generated by Django 4.2.14 on 2024-07-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0004_alter_playerrating_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
    ]
