# Generated by Django 4.2.14 on 2024-08-11 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0005_alter_player_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="date",
        ),
        migrations.AlterField(
            model_name="discipline",
            name="rules",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rules/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="rules",
            ),
        ),
        migrations.CreateModel(
            name="TeamSportRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="olympic_warriors.discipline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="round",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round",
                to="olympic_warriors.teamsportround",
            ),
            preserve_default=False,
        ),
    ]
