# Generated by Django 4.2.14 on 2024-07-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0005_remove_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='olympic_warriors.edition'),
            preserve_default=False,
        ),
    ]
