# Generated by Django 4.2.14 on 2024-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0006_remove_game_date_alter_discipline_rules_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsportround",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
