# Generated by Django 4.2.14 on 2024-08-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0007_teamsportround_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discipline",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
