# Generated by Django 4.2.14 on 2024-08-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0008_alter_discipline_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamresult",
            name="score",
        ),
        migrations.AddField(
            model_name="teamresult",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamresult",
            name="result_type",
            field=models.CharField(
                choices=[("PTS", "Points"), ("TIM", "Time")],
                default="PTS",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamresult",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
