# Generated by Django 4.2.14 on 2024-08-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0009_remove_teamresult_score_teamresult_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blindtestguess",
            name="blindtest",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blindtest",
                to="olympic_warriors.blindtest",
            ),
            preserve_default=False,
        ),
    ]
