# Generated by Django 4.2.15 on 2024-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0011_discipline_reveal_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blindtestguess",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="blindtestguess",
            name="is_valid",
        ),
        migrations.AddField(
            model_name="blindtestguess",
            name="artist",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blindtestguess",
            name="is_artist_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blindtestguess",
            name="is_song_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blindtestguess",
            name="song",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
