# Generated by Django 4.2.14 on 2024-08-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0012_remove_blindtestguess_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rugbyevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("STA", "Start"),
                    ("END", "End"),
                    ("TRY", "Try"),
                    ("STL", "Steal"),
                    ("TKL", "Tackle"),
                    ("FOL", "Foul"),
                    ("OUT", "Out"),
                ],
                max_length=3,
            ),
        ),
    ]
