# Generated by Django 4.2.14 on 2024-08-29 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0012_remove_blindtestguess_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blindtestguess",
            name="blindtest",
        ),
        migrations.CreateModel(
            name="BlindtestRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "blindtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blindtest",
                        to="olympic_warriors.blindtest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blindtestguess",
            name="blindtest_round",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blindtest_round",
                to="olympic_warriors.blindtestround",
            ),
            preserve_default=False,
        ),
    ]
