# Generated by Django 4.2.15 on 2024-08-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0013_remove_blindtestguess_blindtest_blindtestround_and_more'),
        ('olympic_warriors', '0015_alter_dodgeballevent_event_type'),
    ]

    operations = [
    ]
