# Generated by Django 4.2.19 on 2025-07-29 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0016_merge_20240830_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='max_rounds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='max rounds'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='pairing_system',
            field=models.CharField(choices=[('RR', 'Round Robin'), ('SW', 'Swiss'), ('NO', 'None')], default='NO', max_length=2, verbose_name='pairing system'),
        ),
        migrations.AlterField(
            model_name='blindtestguess',
            name='artist',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blindtestguess',
            name='song',
            field=models.CharField(default='', max_length=255),
        ),
    ]
