# Generated by Django 4.2.19 on 2025-08-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0019_teamsportround_is_over_alter_discipline_result_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petanque',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
    ]
