# Generated by Django 4.2.19 on 2025-08-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0020_petanque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.AlterField(
            model_name='teamsportround',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='olympic_warriors.discipline'),
        ),
    ]
