# Generated by Django 4.2.19 on 2025-08-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0021_basketball_alter_teamsportround_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyQuizz',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
    ]
