# Generated by Django 4.2.19 on 2026-09-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0025_generalculturequizz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darts',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
    ]
