# Generated by Django 4.2.19 on 2026-09-22 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0026_darts'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='photos_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
