# Generated by Django 4.2.19 on 2026-09-22 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0028_game_is_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='score 1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='score 2'),
        ),
    ]
