# Generated by Django 4.2.19 on 2026-09-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0029_game_score_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindfoldedObstacleCourse',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='BurgerQuizz',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='DiscThrow',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='Frisbee',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='Geoguessr',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='Handball',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='JumpingRope',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
        migrations.CreateModel(
            name='Volleyball',
            fields=[
                ('discipline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='olympic_warriors.discipline')),
            ],
            bases=('olympic_warriors.discipline',),
        ),
    ]
