# Generated by Django 4.2.19 on 2026-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0029_game_score_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='final_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
