# Generated by Django 4.2.19 on 2026-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olympic_warriors", "0031_team_final_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blindtestguess",
            name="artist",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="blindtestguess",
            name="song",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
