# Generated by Django 4.2.19 on 2026-09-23 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_refresh_row(apps, schema_editor):
    """The one BadgeRefresh row badges.refresh() locks."""
    apps.get_model("olympic_warriors", "BadgeRefresh").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("olympic_warriors", "0032_blindtestguess_blank_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeRefresh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refreshed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("champion", "Champion"),
                            ("runner-up", "Dauphin"),
                            ("bronze", "Bronze"),
                            ("chocolate", "Médaille en chocolat"),
                            ("wooden-spoon", "Cuillère de bois"),
                            ("back-to-back", "Doublé"),
                            ("threepeat", "Triplé"),
                            ("dynasty", "Dynastie"),
                            ("phoenix", "Phénix"),
                            ("legend", "Légende"),
                            ("podium-regular", "Abonné au podium"),
                            ("full-set", "Collection complète"),
                            ("eternal-second", "Poulidor"),
                            ("janus", "Janus"),
                            ("comeback", "Remontada"),
                            ("on-the-rise", "Ascension"),
                            ("icarus", "Icare"),
                            ("lucky-charm", "Porte-bonheur"),
                            ("rookie", "Bizut"),
                            ("veteran", "Vétéran"),
                            ("argonaut", "Argonaute"),
                            ("ever-present", "Pénélope"),
                            ("homecoming", "Ulysse"),
                            ("globetrotter", "Globe-trotteur"),
                            ("comrades", "Compagnons d'armes"),
                            ("networker", "Rassembleur"),
                            ("goat", "G.O.A.T"),
                            ("alone-at-the-top", "Seul au sommet"),
                            ("hall-of-fame-podium", "Podium du panthéon"),
                            ("hall-of-famer", "Entrée au panthéon"),
                            ("reign", "Règne"),
                            ("kingslayer", "Régicide"),
                            ("rocket", "Fusée"),
                            ("specialist", "Spécialiste"),
                            ("all-rounder", "Touche-à-tout"),
                            ("decathlete", "Décathlonien"),
                            ("brains-and-brawn", "Tête et jambes"),
                            ("clean-sweep", "Razzia"),
                            ("metronome", "Métronome"),
                            ("uncrowned", "Sans couronne"),
                            ("photo-finish", "Photo-finish"),
                            ("athena", "Athéna"),
                            ("apollo", "Apollon"),
                            ("artemis", "Artémis"),
                            ("hermes", "Hermès"),
                            ("heracles", "Héraclès"),
                            ("theseus", "Thésée"),
                            ("ares", "Arès"),
                            ("hades", "Hadès"),
                            ("dionysus", "Dionysos"),
                            ("olympus", "Olympe"),
                            ("unbeaten", "Invaincu"),
                            ("perfect-run", "Sans faute"),
                            ("shutout", "Cadenas"),
                            ("steamroller", "Rouleau compresseur"),
                            ("golden-whistle", "Sifflet d'or"),
                            ("perfect-pitch", "Oreille absolue"),
                            ("mvp", "MVP"),
                            ("fair-play", "Fair-play"),
                            ("hype", "Ambianceur"),
                            ("costume", "Plus beau déguisement"),
                            ("wounded", "Blessé de guerre"),
                            ("torchbearer", "Porteur de flamme"),
                        ],
                        max_length=32,
                    ),
                ),
                ("tier", models.PositiveSmallIntegerField(default=0)),
                (
                    "discipline",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_manual", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="olympic_warriors.edition",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="badge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_manual", False)),
                fields=("user", "code", "edition", "tier", "discipline", "partner"),
                name="badge_unique_computed",
            ),
        ),
        migrations.RunPython(create_refresh_row, migrations.RunPython.noop),
    ]
