# Generated by Django 4.2.19 on 2026-09-24 10:24

from django.db import migrations, models


def delete_removed_badges(apps, schema_editor):
    """golden-whistle and globetrotter are no longer awarded; drop any stored row of
    either, computed or manual."""
    Badge = apps.get_model("olympic_warriors", "Badge")
    Badge.objects.filter(code__in=["golden-whistle", "globetrotter"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("olympic_warriors", "0033_badges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="code",
            field=models.CharField(
                choices=[
                    ("champion", "Champion"),
                    ("runner-up", "Dauphin"),
                    ("bronze", "Bronze"),
                    ("chocolate", "Médaille en chocolat"),
                    ("wooden-spoon", "Cuillère de bois"),
                    ("back-to-back", "Doublé"),
                    ("threepeat", "Triplé"),
                    ("dynasty", "Dynastie"),
                    ("phoenix", "Phénix"),
                    ("legend", "Légende"),
                    ("podium-regular", "Abonné au podium"),
                    ("full-set", "Collection complète"),
                    ("eternal-second", "Poulidor"),
                    ("janus", "Janus"),
                    ("comeback", "Remontada"),
                    ("on-the-rise", "Ascension"),
                    ("icarus", "Icare"),
                    ("lucky-charm", "Porte-bonheur"),
                    ("rookie", "Bizut"),
                    ("veteran", "Vétéran"),
                    ("argonaut", "Argonaute"),
                    ("ever-present", "Pénélope"),
                    ("homecoming", "Ulysse"),
                    ("comrades", "Compagnons d'armes"),
                    ("networker", "Rassembleur"),
                    ("goat", "G.O.A.T"),
                    ("alone-at-the-top", "Seul au sommet"),
                    ("hall-of-fame-podium", "Podium du panthéon"),
                    ("hall-of-famer", "Entrée au panthéon"),
                    ("reign", "Règne"),
                    ("kingslayer", "Régicide"),
                    ("rocket", "Fusée"),
                    ("specialist", "Spécialiste"),
                    ("all-rounder", "Touche-à-tout"),
                    ("decathlete", "Décathlonien"),
                    ("brains-and-brawn", "Tête et jambes"),
                    ("clean-sweep", "Razzia"),
                    ("metronome", "Métronome"),
                    ("uncrowned", "Sans couronne"),
                    ("photo-finish", "Photo-finish"),
                    ("athena", "Athéna"),
                    ("apollo", "Apollon"),
                    ("artemis", "Artémis"),
                    ("hermes", "Hermès"),
                    ("heracles", "Héraclès"),
                    ("theseus", "Thésée"),
                    ("ares", "Arès"),
                    ("hades", "Hadès"),
                    ("dionysus", "Dionysos"),
                    ("olympus", "Olympe"),
                    ("unbeaten", "Invaincu"),
                    ("perfect-run", "Sans faute"),
                    ("shutout", "Cadenas"),
                    ("steamroller", "Rouleau compresseur"),
                    ("perfect-pitch", "Oreille absolue"),
                    ("mvp", "MVP"),
                    ("fair-play", "Fair-play"),
                    ("hype", "Ambianceur"),
                    ("costume", "Plus beau déguisement"),
                    ("wounded", "Blessé de guerre"),
                    ("torchbearer", "Porteur de flamme"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(delete_removed_badges, migrations.RunPython.noop),
    ]
