# Generated by Django 4.2.19 on 2026-09-24 15:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("olympic_warriors", "0034_remove_golden_whistle_globetrotter"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="avatars/")),
                ("photo_small", models.ImageField(blank=True, upload_to="avatars/")),
                ("photo_locked", models.BooleanField(default=False)),
                (
                    "showcase",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("champion", "Champion"),
                                ("runner-up", "Dauphin"),
                                ("bronze", "Bronze"),
                                ("chocolate", "Médaille en chocolat"),
                                ("wooden-spoon", "Cuillère de bois"),
                                ("back-to-back", "Doublé"),
                                ("threepeat", "Triplé"),
                                ("dynasty", "Dynastie"),
                                ("phoenix", "Phénix"),
                                ("legend", "Légende"),
                                ("podium-regular", "Abonné au podium"),
                                ("full-set", "Collection complète"),
                                ("eternal-second", "Poulidor"),
                                ("janus", "Janus"),
                                ("comeback", "Remontada"),
                                ("on-the-rise", "Ascension"),
                                ("icarus", "Icare"),
                                ("lucky-charm", "Porte-bonheur"),
                                ("rookie", "Bizut"),
                                ("veteran", "Vétéran"),
                                ("argonaut", "Argonaute"),
                                ("ever-present", "Pénélope"),
                                ("homecoming", "Ulysse"),
                                ("comrades", "Compagnons d'armes"),
                                ("networker", "Rassembleur"),
                                ("goat", "G.O.A.T"),
                                ("alone-at-the-top", "Seul au sommet"),
                                ("hall-of-fame-podium", "Podium du panthéon"),
                                ("hall-of-famer", "Entrée au panthéon"),
                                ("reign", "Règne"),
                                ("kingslayer", "Régicide"),
                                ("rocket", "Fusée"),
                                ("specialist", "Spécialiste"),
                                ("all-rounder", "Touche-à-tout"),
                                ("decathlete", "Décathlonien"),
                                ("brains-and-brawn", "Tête et jambes"),
                                ("clean-sweep", "Razzia"),
                                ("metronome", "Métronome"),
                                ("uncrowned", "Sans couronne"),
                                ("photo-finish", "Photo-finish"),
                                ("athena", "Athéna"),
                                ("apollo", "Apollon"),
                                ("artemis", "Artémis"),
                                ("hermes", "Hermès"),
                                ("heracles", "Héraclès"),
                                ("theseus", "Thésée"),
                                ("ares", "Arès"),
                                ("hades", "Hadès"),
                                ("dionysus", "Dionysos"),
                                ("olympus", "Olympe"),
                                ("unbeaten", "Invaincu"),
                                ("perfect-run", "Sans faute"),
                                ("shutout", "Cadenas"),
                                ("steamroller", "Rouleau compresseur"),
                                ("perfect-pitch", "Oreille absolue"),
                                ("mvp", "MVP"),
                                ("fair-play", "Fair-play"),
                                ("hype", "Ambianceur"),
                                ("costume", "Plus beau déguisement"),
                                ("wounded", "Blessé de guerre"),
                                ("torchbearer", "Porteur de flamme"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=list,
                        size=3,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
