# Generated by Django 4.2.15 on 2026-09-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0035_badge_master'),
        ('olympic_warriors', '0035_userprofile'),
    ]

    operations = [
    ]
