# Generated by Django 4.2.19 on 2026-09-30 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("olympic_warriors", "0038_userprofile_showcase_five"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("champion", "Champion"),
                            ("runner-up", "Dauphin"),
                            ("bronze", "Bronze"),
                            ("chocolate", "Médaille en chocolat"),
                            ("wooden-spoon", "Cuillère de bois"),
                            ("back-to-back", "Doublé"),
                            ("threepeat", "Triplé"),
                            ("dynasty", "Dynastie"),
                            ("phoenix", "Phénix"),
                            ("legend", "Légende"),
                            ("podium-regular", "Abonné au podium"),
                            ("full-set", "Collection complète"),
                            ("eternal-second", "Poulidor"),
                            ("janus", "Janus"),
                            ("comeback", "Remontada"),
                            ("on-the-rise", "Ascension"),
                            ("icarus", "Icare"),
                            ("lucky-charm", "Porte-bonheur"),
                            ("rookie", "Bizut"),
                            ("veteran", "Vétéran"),
                            ("argonaut", "Argonaute"),
                            ("ever-present", "Pénélope"),
                            ("homecoming", "Ulysse"),
                            ("comrades", "Compagnons d'armes"),
                            ("networker", "Rassembleur"),
                            ("goat", "G.O.A.T"),
                            ("alone-at-the-top", "Seul au sommet"),
                            ("hall-of-fame-podium", "Podium du panthéon"),
                            ("hall-of-famer", "Entrée au panthéon"),
                            ("reign", "Règne"),
                            ("kingslayer", "Régicide"),
                            ("rocket", "Fusée"),
                            ("specialist", "Spécialiste"),
                            ("master", "Maître"),
                            ("all-rounder", "Touche-à-tout"),
                            ("decathlete", "Décathlonien"),
                            ("brains-and-brawn", "Tête et jambes"),
                            ("clean-sweep", "Razzia"),
                            ("metronome", "Métronome"),
                            ("uncrowned", "Sans couronne"),
                            ("photo-finish", "Photo-finish"),
                            ("athena", "Athéna"),
                            ("apollo", "Apollon"),
                            ("artemis", "Artémis"),
                            ("hermes", "Hermès"),
                            ("heracles", "Héraclès"),
                            ("theseus", "Thésée"),
                            ("ares", "Arès"),
                            ("hades", "Hadès"),
                            ("dionysus", "Dionysos"),
                            ("olympus", "Olympe"),
                            ("unbeaten", "Invaincu"),
                            ("perfect-run", "Sans faute"),
                            ("shutout", "Cadenas"),
                            ("steamroller", "Rouleau compresseur"),
                            ("perfect-pitch", "Oreille absolue"),
                            ("mvp", "MVP"),
                            ("fair-play", "Fair-play"),
                            ("hype", "Ambianceur"),
                            ("costume", "Plus beau déguisement"),
                            ("wounded", "Blessé de guerre"),
                            ("torchbearer", "Porteur de flamme"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.PositiveIntegerField(null=True)),
                ("best", models.PositiveIntegerField(null=True)),
                ("reachable", models.BooleanField(default=True)),
                (
                    "discipline",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("year", models.PositiveIntegerField(null=True)),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="badgeprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "code"), name="progress_unique"
            ),
        ),
    ]
