# Generated by Django 4.2.19 on 2026-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0039_badgeprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
