# Generated by Django 4.2.19 on 2026-10-04 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0040_userprofile_anonymized'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='dates_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='attendance_confirmed',
            field=models.BooleanField(default=False, help_text="The player's own tick: paid and will be there. Nothing checks it."),
        ),
        migrations.AddField(
            model_name='player',
            name='dietary_restrictions',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='player',
            name='global_level',
            field=models.IntegerField(blank=True, help_text='Raw global estimate; `rating` blends it, so it cannot be recovered from it.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='player',
            name='sport_frequency',
            field=models.CharField(blank=True, choices=[('rare', "Moins d'une fois par mois"), ('monthly', "Moins d'une fois par semaine mais plusieurs fois par mois"), ('hour', 'Environ une heure par semaine'), ('two_hours', 'Au moins deux heures par semaine'), ('four_hours', 'Au moins quatre heures par semaine')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='team_wishes',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.CreateModel(
            name='RegistrationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=4)),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_warriors.edition')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('sport', models.CharField(max_length=80)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Débutant'), ('amateur', 'Amateur'), ('club', 'Club'), ('competition', 'Compétition')], default='', max_length=12)),
                ('practice', models.CharField(blank=True, choices=[('no_longer', 'Ne pratique plus'), ('occasionally', 'Pratique occasionnelle'), ('regularly', 'Pratique régulière')], default='', max_length=12)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(200)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_warriors.player')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrationskill',
            constraint=models.UniqueConstraint(fields=('edition', 'identifier'), name='registration_skill_unique_identifier'),
        ),
    ]
