# Generated by Django 4.2.19 on 2026-10-05 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympic_warriors', '0042_seed_registration_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='registration_closes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='registration_intro_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='edition',
            name='registration_intro_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='edition',
            name='registration_opens',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='skills_month_en',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='edition',
            name='skills_month_fr',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_warriors.edition')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='lateregistration',
            constraint=models.UniqueConstraint(fields=('user', 'edition'), name='late_registration_unique'),
        ),
    ]
