# Generated by Django 4.2.19 on 2026-10-05 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0043_registration_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_avoid',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Préfère éviter'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_with',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Souhaite être avec'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_wishes',
            field=models.TextField(blank=True, default='', help_text='Combined free text of the CSV registration (up to 2026). The form no longer writes it.', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name="Souhaits d'équipe (ancien format)"),
        ),
    ]
