# Generated by Django 4.2.19 on 2026-10-05 13:48

from django.db import migrations, models


OLD_TO_NEW = {"beginner": "fun", "amateur": "informal", "club": "club", "competition": "league"}


def to_ladder(apps, schema_editor):
    """The first four answers mixed skill and setting; each maps to the nearest step of the ladder."""
    PlayerSport = apps.get_model("olympic_warriors", "PlayerSport")
    for old, new in OLD_TO_NEW.items():
        if old != new:
            PlayerSport.objects.filter(level=old).update(level=new)


def to_old_choices(apps, schema_editor):
    """Back to the first four: the two top steps fold into 'competition'."""
    PlayerSport = apps.get_model("olympic_warriors", "PlayerSport")
    back = {"fun": "beginner", "informal": "amateur", "league": "competition", "regional": "competition"}
    for new, old in back.items():
        PlayerSport.objects.filter(level=new).update(level=old)


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_warriors', '0044_player_team_with_avoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersport',
            name='level',
            field=models.CharField(blank=True, choices=[('fun', 'Pour le plaisir, entre amis'), ('informal', 'Régulièrement, hors club'), ('club', 'En club, sans compétition'), ('league', 'En club, avec compétitions'), ('regional', 'Niveau régional ou supérieur')], default='', max_length=12),
        ),
        migrations.RunPython(to_ladder, to_old_choices),
    ]
