# Generated by Django 4.2.19 on 2026-10-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympic_warriors', '0045_sport_level_ladder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_draft', to='olympic_warriors.edition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
