# Generated by Django 4.2.7 on 2024-04-20 21:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("olympic_warriors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edition",
            name="teams",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="team",
        ),
        migrations.AddField(
            model_name="edition",
            name="registration_form",
            field=models.FileField(
                blank=True, null=True, upload_to="registration_forms/"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="olympic_warriors.player",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captain",
                to="olympic_warriors.player",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="edition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="olympic_warriors.edition",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.CreateModel(
            name="PlayerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("identifier", models.CharField(max_length=4)),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="olympic_warriors.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="olympic_warriors.edition",
                    ),
                ),
                (
                    "referees",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referees",
                        to="olympic_warriors.team",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team1",
                        to="olympic_warriors.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team2",
                        to="olympic_warriors.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="olympic_warriors.edition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rugby",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="olympic_warriors.event",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="olympic_warriors.team",
                    ),
                ),
            ],
            bases=("olympic_warriors.event",),
        ),
    ]
