name: Django Tests and Linting

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker-compose
          pip install pylint pylint-django

      - name: Run pylint
        run: |
          pylint --load-plugins pylint_django --ignore=lib server/

      - name: Build and start Docker containers
        run: docker-compose up -d

      - name: Wait for the database to be ready
        run: |
          until docker-compose exec db pg_isready -U user -d mydb-dev; do
            sleep 1
          done

      - name: Run migrations
        run: docker-compose exec server python manage.py migrate

    # - name: Run Django tests
    #  run: docker-compose exec server python manage.py test

      - name: Stop Docker containers
        if: always()
        run: docker-compose down
